### ISSUE TITLE
boxart location incorrect when selecting rom subdirectory

### ISSUE THREAD

**Issue by Nomelas** [KirovAir/TwilightBoxart#1]
Looks like when you change the roms location to be anything but the root of the SD card, it updates the path of the boxart location to match. You can even see from your example screenshot that it happens :)

this is not correct, the path should always be $drive:\_nds\TWiLightMenu\boxart

I haven't tried on Mac, but this is reproducible on Windows.

**Comment by KirovAir** [comment]
Should be fixed in 0.2 ;)
https://github.com/KirovAir/TwilightBoxart/releases/tag/0.2
