### ISSUE TITLE
 An error occurred while sending the request. The remote name could not be resolved: 'boxart.kirovair.com'

### ISSUE THREAD

**Issue by mahmoudnadi** [KirovAir/TwilightBoxart#18]
Keep getting this error for every rom that it searches for. Screenshot attached
<img width="385" alt="twilightboxart" src="https://github.com/KirovAir/TwilightBoxart/assets/52580627/5961394d-3b58-4243-9800-30a09a4985c7">

**Comment by ffrancoa** [comment]
Duplicated from https://github.com/KirovAir/TwilightBoxart/issues/17. We're still waiting for a solution

**Comment by mahmoudnadi** [comment]
@ffrancoa the error in #17 was worded differently so didnt want to assume it was the same issue. No worries though, hope a fix is found soon. Its weird though as I didnt have this issue last week.

**Comment by unrxmarkable** [comment]
https://gbatemp.net/threads/twilight-menu-updater-not-downloading-covers.588495/
Download link in this thread seems to be working for some reason...

**Comment by ffrancoa** [comment]
> https://gbatemp.net/threads/twilight-menu-updater-not-downloading-covers.588495/ Download link in this thread seems to be working for some reason...

Works like a charm, thanks dude. It appears to be an early build, at least prior to the last one that gives this issue.

**Comment by unrxmarkable** [comment]
Hah, no worries, just got a DSi for the first time so I was looking around for stuff like this :D

**Comment by mahmoudnadi** [comment]
Yeah that one worked great, thanks
