### ISSUE TITLE
Wrong path under Linux

### ISSUE THREAD

**Issue by limbusdev** [KirovAir/TwilightBoxart#2]
Hi there,

great tool. Thank you! I noticed a small issue in the `TwilightBoxart.ini` that causes problems under Linux (and Mac OS I guess). I guess a separate ini for those systems is needed.

Instead of:

```ini
﻿; These are the default config values.
[Config]
SdRoot=
BoxartPath={sdroot}\_nds\TWiLightMenu\boxart
BoxartWidth=128
BoxartHeight=115
AdjustAspectRatio=true
```

we need the following for Linux:

```ini
﻿; These are the default config values.
[Config]
SdRoot=
BoxartPath={sdroot}_nds/TWiLightMenu/boxart
BoxartWidth=128
BoxartHeight=115
AdjustAspectRatio=true
```

Hope, this helps. Keep up the great work! :)

**Comment by KirovAir** [comment]
I'll have this changed in the next release. :) Thanks.
