### ISSUE TITLE
It breaks with uppercase file extensions.

### ISSUE THREAD

**Issue by MatLegat** [KirovAir/TwilightBoxart#3]
I've been using your tool for donloading boxart for various ROM games that I have, and I've fount an issue with your tool:
When a file extension is in uppercase it recognises that it is a rom (tries to download a boxart for it) but then it can't check the type of it.
This issues happens with various rom types (`.GG`, `.SMS`, `.GEN`, etc...) and renaming the files for them to have a lowercase extension (`.sms`, `.gen`, ...) gets rid of this error (at least on my tests).

Output extracted from the tool with an example of this error:
```
01:21:28 - Searching art for Bram Stoker's Dracula.SMS.. 
01:21:28 - Something bad happened: Unknown ROM type.
```

Anyway, thanks for this much useful tool for TwilightMenu users :)

**Comment by KirovAir** [comment]
I'll have this fixed in the next version. :)
